### ISSUE TITLE
Switching Between Images

### ISSUE THREAD

**Issue by zwickerr** [BernhardWebstudio/DataShot_DesktopApp#8] opened 2019-10-23 10:26 UTC
- [x] Switching between images only works for the first specimen that was opened. After changing to the next specimen with the arrow buttons the second image of the first specimen is shown when trying to switch images.

- [x] Switching between images resizes the window when in full screen

**Comment by GenieTim** [comment] 2019-10-27 18:16
The first change request is a duplicate of #9, correct?

**Comment by zwickerr** [comment] 2019-10-28 08:17
Yes, it seems to be fixed in 1.9.3.

The window does not leave full screen anymore either when switching between images.

**Closed as completed** 2019-10-28 11:27 UTC
Labels: bug
