### ISSUE TITLE
Unable to edit content after saving document

### ISSUE THREAD

**Issue by DataDigitalizer** [BernhardWebstudio/DataShot_DesktopApp#25] opened 2020-01-07 13:31 UTC
If you edit a saved document and afterwards want to delete a row in "Numbers & more", "Collectors" or "Determinations", you can't save the document again without getting an error message. The function "Copy & Paste" doesn't work either for those cases.

Kind regards,
DataDigitalizer

**Comment by GenieTim** [comment] 2020-01-07 13:33
Hi, thanks for the issue. Could this be a duplicate of #24 ?

**Comment by DataDigitalizer** [comment] 2020-01-07 14:41
Yes it is! Thanks for the remark.

**Comment by GenieTim** [comment] 2020-03-08 09:30
According to #27, if I understand correctly (and test correctly myself), this is fixed, right?

**Closed as completed by GenieTim** 2020-03-08 09:30 UTC
Labels: bug, duplicate
